
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
 
using System.Reflection;
using System.Resources;

[assembly: AssemblyProduct("Accord.NET Framework")]
[assembly: AssemblyCopyright("Copyright © Accord.NET authors, 2009-2015")]
[assembly: AssemblyCompany("Accord.NET")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en")]

[assembly: AssemblyVersion("3.1.0")]
[assembly: AssemblyInformationalVersion("3.1.0")]
[assembly: AssemblyFileVersion("3.1.0.5591")]
